package main

import (
	"fmt"
	"html/template"
	"net/http"
)

var home = template.Must(template.ParseFiles("Html_Css/index.html"))

type AutoGenerated struct {
	ID                   string `json:"id"`
	Title                string `json:"title"`
	Thumbnail            string `json:"thumbnail"`
	ShortDescription     string `json:"short_description"`
	GameURL              string `json:"game_url"`
	Genre                string `json:"genre"`
	Platform             string `json:"platform"`
	Publisher            string `json:"publisher"`
	Developer            string `json:"developer"`
	ReleaseDate          string `json:"release_date"`
	FreetogameProfileURL string `json:"freetogame_profile_url"`
}

func main() {
	style := http.FileServer(http.Dir("Html_Css"))
	http.Handle("/Html_Css/", http.StripPrefix("/Html_Css", style))
	http.HandleFunc("/Home", HttpHandlerHome)
	http.ListenAndServe(":80", nil)
}

func HttpHandlerHome(w http.ResponseWriter, r *http.Request) {

	var StructId AutoGenerated

	data := AutoGenerated{
		Genre:    fmt.Sprintf(StructId.Genre),
		Title:    fmt.Sprintf(StructId.Title),
		Platform: fmt.Sprintf(StructId.Platform),
	}
	home.Execute(w, data)
}
